In [115]:
!pip install category_encoders

Requirement already satisfied: category_encoders in c:\users\as\anaconda3\lib\site-packages (2.6.2)
Requirement already satisfied: patsy>=0.5.1 in c:\users\as\anaconda3\lib\site-packages (from category_encoders) (0.5.2)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\as\anaconda3\lib\site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\as\anaconda3\lib\site-packages (from category_encoders) (1.9.1)
Requirement already satisfied: pandas>=1.0.5 in c:\users\as\anaconda3\lib\site-packages (from category_encoders) (1.4.4)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\as\anaconda3\lib\site-packages (from category_encoders) (0.13.2)
Requirement already satisfied: numpy>=1.14.0 in c:\users\as\anaconda3\lib\site-packages (from category_encoders) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\as\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\as\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: six in c:\users\as\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=0.11 in c:\users\as\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\as\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.2.0)
Requirement already satisfied: packaging>=21.3 in c:\users\as\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\as\anaconda3\lib\site-packages (from packaging>=21.3->statsmodels>=0.9.0->category_encoders) (3.0.9)

In [116]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\as\anaconda3\lib\site-packages (2.0.1)
Requirement already satisfied: scipy in c:\users\as\anaconda3\lib\site-packages (from xgboost) (1.9.1)
Requirement already satisfied: numpy in c:\users\as\anaconda3\lib\site-packages (from xgboost) (1.21.5)

In [117]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\as\anaconda3\lib\site-packages (4.1.0)
Requirement already satisfied: scipy in c:\users\as\anaconda3\lib\site-packages (from lightgbm) (1.9.1)
Requirement already satisfied: numpy in c:\users\as\anaconda3\lib\site-packages (from lightgbm) (1.21.5)

In [118]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
import xgboost as xgb
import lightgbm as lgb
from sklearn.metrics import accuracy_score

In [119]:
df = pd.read_csv(r'C:\Users\as\Documents\1 Hamoye Intenship\WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [120]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [121]:
df.shape

(7043, 21)

In [122]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [123]:
df.duplicated().sum()

0

In [124]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [125]:
df['TotalCharges'].isna().sum()

0

In [126]:
#numerical = numerical.replace('', np.nan)

df['TotalCharges']=  pd.to_numeric(df['TotalCharges'], errors='coerce')
df['tenure'] =  pd.to_numeric(df['tenure'], errors='coerce')

In [127]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [128]:
df[ 'Churn'].unique()

array(['No', 'Yes'], dtype=object)

In [129]:
import category_encoders as ce

In [130]:
ChurnCoder = ce.OrdinalEncoder(cols=['Churn'], return_df =True, 
                            mapping = [{'col':'Churn',
                                        'mapping':{'Yes':1,'No':0}}])
df['Churn_encoded']= ChurnCoder.fit_transform(df['Churn'])

In [131]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Churn_encoded
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,0
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,0

In [132]:
df = df[['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges',
       'Churn_encoded']]

In [133]:
categorical = df[['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService','OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies','Contract', 'PaperlessBilling', 'PaymentMethod']]
numerical = df[['tenure', 'MonthlyCharges', 'TotalCharges']]

In [134]:
categorical.shape[1]

16

In [135]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()
X_scaled = scaler.fit_transform(numerical)

column_names = ['tenure', 'MonthlyCharges', 'TotalCharges']
X_scaled_df = pd.DataFrame(X_scaled, columns=column_names)

In [136]:
X_scaled_df

        tenure  MonthlyCharges  TotalCharges
0    -1.277445       -1.160323     -0.994194
1     0.066327       -0.259629     -0.173740
2    -1.236724       -0.362660     -0.959649
3     0.514251       -0.746535     -0.195248
4    -1.236724        0.197365     -0.940457
...        ...             ...           ...
7038 -0.340876        0.665992     -0.129180
7039  1.613701        1.277533      2.241056
7040 -0.870241       -1.168632     -0.854514
7041 -1.155283        0.320338     -0.872095
7042  1.369379        1.358961      2.012344

[7043 rows x 3 columns]

In [138]:
from sklearn.preprocessing import OneHotEncoder

categorical_data = df[['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService','OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies','Contract', 'PaperlessBilling', 'PaymentMethod']]

catCols =list(categorical_data.columns)
encoder = ce.OneHotEncoder(cols=catCols,handle_unknown ='return_nan', return_df = True, use_cat_names = True)

encoded_data = encoder.fit_transform(categorical_data)

In [139]:
encoded_data

,gender_Female,gender_Male,SeniorCitizen_0.0,SeniorCitizen_1.0,Partner_Yes,Partner_No,Dependents_No,Dependents_Yes,PhoneService_No,PhoneService_Yes,...,StreamingMovies_No internet service,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaperlessBilling_No,PaymentMethod_Electronic check,PaymentMethod_Mailed check,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic)
0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
7039,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
7040,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
7041,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
7042,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0

In [140]:
newDf = pd.concat([encoded_data,X_scaled_df],axis = 1)

In [141]:
newDf

,gender_Female,gender_Male,SeniorCitizen_0.0,SeniorCitizen_1.0,Partner_Yes,Partner_No,Dependents_No,Dependents_Yes,PhoneService_No,PhoneService_Yes,...,Contract_Two year,PaperlessBilling_Yes,PaperlessBilling_No,PaymentMethod_Electronic check,PaymentMethod_Mailed check,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),tenure,MonthlyCharges,TotalCharges
0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,-1.277445,-1.160323,-0.994194
1,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.066327,-0.259629,-0.173740
2,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,-1.236724,-0.362660,-0.959649
3,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.514251,-0.746535,-0.195248
4,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,-1.236724,0.197365,-0.940457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,-0.340876,0.665992,-0.129180
7039,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.613701,1.277533,2.241056
7040,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.870241,-1.168632,-0.854514
7041,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,-1.155283,0.320338,-0.872095
7042,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.369379,1.358961,2.012344

In [142]:
newDf.columns

Index(['gender_Female', 'gender_Male', 'SeniorCitizen_0.0',
       'SeniorCitizen_1.0', 'Partner_Yes', 'Partner_No', 'Dependents_No',
       'Dependents_Yes', 'PhoneService_No', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_No',
       'MultipleLines_Yes', 'InternetService_DSL',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No', 'OnlineSecurity_Yes',
       'OnlineSecurity_No internet service', 'OnlineBackup_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'DeviceProtection_No', 'DeviceProtection_Yes',
       'DeviceProtection_No internet service', 'TechSupport_No',
       'TechSupport_Yes', 'TechSupport_No internet service', 'StreamingTV_No',
       'StreamingTV_Yes', 'StreamingTV_No internet service',
       'StreamingMovies_No', 'StreamingMovies_Yes',
       'StreamingMovies_No internet service', 'Contract_Month-to-month',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaperlessBilling_No', 'PaymentMethod_Electronic check',
       'PaymentMethod_Mailed check', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)', 'tenure', 'MonthlyCharges',
       'TotalCharges'],
      dtype='object')

In [143]:
newDf['Churn']= df.Churn_encoded

In [144]:
newDf

,gender_Female,gender_Male,SeniorCitizen_0.0,SeniorCitizen_1.0,Partner_Yes,Partner_No,Dependents_No,Dependents_Yes,PhoneService_No,PhoneService_Yes,...,PaperlessBilling_Yes,PaperlessBilling_No,PaymentMethod_Electronic check,PaymentMethod_Mailed check,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),tenure,MonthlyCharges,TotalCharges,Churn
0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,-1.277445,-1.160323,-0.994194,0
1,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.066327,-0.259629,-0.173740,0
2,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,-1.236724,-0.362660,-0.959649,1
3,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.514251,-0.746535,-0.195248,0
4,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,-1.236724,0.197365,-0.940457,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,-0.340876,0.665992,-0.129180,0
7039,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.613701,1.277533,2.241056,0
7040,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,-0.870241,-1.168632,-0.854514,0
7041,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,-1.155283,0.320338,-0.872095,1
7042,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.369379,1.358961,2.012344,0

In [145]:
newDf.isna().sum()

gender_Female                               0
gender_Male                                 0
SeniorCitizen_0.0                           0
SeniorCitizen_1.0                           0
Partner_Yes                                 0
Partner_No                                  0
Dependents_No                               0
Dependents_Yes                              0
PhoneService_No                             0
PhoneService_Yes                            0
MultipleLines_No phone service              0
MultipleLines_No                            0
MultipleLines_Yes                           0
InternetService_DSL                         0
InternetService_Fiber optic                 0
InternetService_No                          0
OnlineSecurity_No                           0
OnlineSecurity_Yes                          0
OnlineSecurity_No internet service          0
OnlineBackup_Yes                            0
OnlineBackup_No                             0
OnlineBackup_No internet service            0
DeviceProtection_No                         0
DeviceProtection_Yes                        0
DeviceProtection_No internet service        0
TechSupport_No                              0
TechSupport_Yes                             0
TechSupport_No internet service             0
StreamingTV_No                              0
StreamingTV_Yes                             0
StreamingTV_No internet service             0
StreamingMovies_No                          0
StreamingMovies_Yes                         0
StreamingMovies_No internet service         0
Contract_Month-to-month                     0
Contract_One year                           0
Contract_Two year                           0
PaperlessBilling_Yes                        0
PaperlessBilling_No                         0
PaymentMethod_Electronic check              0
PaymentMethod_Mailed check                  0
PaymentMethod_Bank transfer (automatic)     0
PaymentMethod_Credit card (automatic)       0
tenure                                      0
MonthlyCharges                              0
TotalCharges                               11
Churn                                       0
dtype: int64

In [151]:
newDf['TotalCharges']=newDf['TotalCharges'].fillna(0)

In [152]:
newDf.isna().sum()

gender_Female                              0
gender_Male                                0
SeniorCitizen_0.0                          0
SeniorCitizen_1.0                          0
Partner_Yes                                0
Partner_No                                 0
Dependents_No                              0
Dependents_Yes                             0
PhoneService_No                            0
PhoneService_Yes                           0
MultipleLines_No phone service             0
MultipleLines_No                           0
MultipleLines_Yes                          0
InternetService_DSL                        0
InternetService_Fiber optic                0
InternetService_No                         0
OnlineSecurity_No                          0
OnlineSecurity_Yes                         0
OnlineSecurity_No internet service         0
OnlineBackup_Yes                           0
OnlineBackup_No                            0
OnlineBackup_No internet service           0
DeviceProtection_No                        0
DeviceProtection_Yes                       0
DeviceProtection_No internet service       0
TechSupport_No                             0
TechSupport_Yes                            0
TechSupport_No internet service            0
StreamingTV_No                             0
StreamingTV_Yes                            0
StreamingTV_No internet service            0
StreamingMovies_No                         0
StreamingMovies_Yes                        0
StreamingMovies_No internet service        0
Contract_Month-to-month                    0
Contract_One year                          0
Contract_Two year                          0
PaperlessBilling_Yes                       0
PaperlessBilling_No                        0
PaymentMethod_Electronic check             0
PaymentMethod_Mailed check                 0
PaymentMethod_Bank transfer (automatic)    0
PaymentMethod_Credit card (automatic)      0
tenure                                     0
MonthlyCharges                             0
TotalCharges                               0
Churn                                      0
dtype: int64

In [163]:
dfArr = newDf.values

X = dfArr[0:7043, 0:46]
y = dfArr[0:7043, 46]

In [164]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2, random_state=1)

In [165]:
# Train a Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=1)
rf_classifier.fit(X_train, y_train)
rf_pred = rf_classifier.predict(X_test)

# Train an Extra Trees Classifier
et_classifier = ExtraTreesClassifier(random_state=1)
et_classifier.fit(X_train, y_train)
et_pred = et_classifier.predict(X_test)

# Train an XGBoost model
xgb_model = xgb.XGBClassifier(random_state=1)
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)

# Train a LightGBM model
lgb_model = lgb.LGBMClassifier(random_state=1)
lgb_model.fit(X_train, y_train)
lgb_pred = lgb_model.predict(X_test)

# Evaluate the models
rf_accuracy = accuracy_score(y_test, rf_pred)
et_accuracy = accuracy_score(y_test, et_pred)
xgb_accuracy = accuracy_score(y_test, xgb_pred)
lgb_accuracy = accuracy_score(y_test, lgb_pred)

# Print the accuracies
print("Random Forest Accuracy:", rf_accuracy)
print("Extra Trees Accuracy:", et_accuracy)
print("XGBoost Accuracy:", xgb_accuracy)
print("LightGBM Accuracy:", lgb_accuracy)

[LightGBM] [Info] Number of positive: 1521, number of negative: 4113
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001124 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 670
[LightGBM] [Info] Number of data points in the train set: 5634, number of used features: 46
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.269968 -> initscore=-0.994785
[LightGBM] [Info] Start training from score -0.994785
Random Forest Accuracy: 0.7913413768630234
Extra Trees Accuracy: 0.7665010645848119
XGBoost Accuracy: 0.801277501774308
LightGBM Accuracy: 0.8147622427253371

In [166]:
model = LogisticRegression() #instatiate the model

model.fit(X_train, y_train)

result = model.score(X_test,y_test)

C:\Users\as\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [167]:
result

0.8119233498935415